version: 2

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt
    - method: setuptools
      path: .
